### ISSUE TITLE
Remove Kavorka Dep?

### ISSUE THREAD

**Issue by frioux** [rustyconover/Amazon-DynamoDB#13]
Amazon::DynamoDB uses Kavorka, which fails on perl 5.22 currently.  Would you be willing to accept a patch that rewrites the kavorka stuff in pure perl or some more stable modules?

**Comment by rustyconover** [comment]
It seems that Kavorka isn't being maintained anymore.  Which make me kind of sad. 

I guess if we wanted to go another way I'd be fine with that.

**Comment by kablamo** [comment]
Toby Ink released a version of Kavorka that compiles on perl 5.26.0 so my guess is you can close this now.

**Comment by frioux** [comment]
I'll close it, but I still think it's a heavyweight dep for just some syntax sugar.
