### ISSUE TITLE
Doesn't accept undef as an item value

### ISSUE THREAD

**Issue by stevecaldwell77** [rustyconover/Amazon-DynamoDB#4]
Trying to call put_item on an item with an undef value, e.g.:

```
$ddb->put_item(
   TableName => $table_name,
   Item => {
     name => 'Test Name'
     email => undef,
   },
   ReturnValues => 'ALL_OLD');
```

throws the error:

```
...did not pass type constraint "ItemType"...
    "ItemType" is a subtype of "Map[AttributeNameType,AttributeValueType]"
    Reference {"__CLASS__" => "CE::LeadRequestTransaction::State","_comple...} did not pass type constraint "Map[AttributeNameType,AttributeValueType]"
    "Map[AttributeNameType,AttributeValueType]" constrains each value in the hash with "AttributeValueType"
    "AttributeValueType" is a subtype of "Defined"
    Undef did not pass type constraint "Defined" (in $_->{"clickouts_only"})
    "Defined" is defined as: (defined($_))
```

You should be able to store these values using DynamoDB's NULL data type:

http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html

**Comment by rustyconover** [comment]
This NULL datatype is newer than the code I wrote and not fully baked into the code.  Neither is Bool, List or Map.  Both would probably be easy to add.  Bool would be tricky, because how does perl know its a bool compared to an integer.

Pull requests welcome...

**Comment by rustyconover** [comment]
You might want to give this a shot:

https://github.com/rustyconover/Amazon-DynamoDB/commit/79c66928e77d1a1187faed3533f1f9ff90286b45

**Comment by rustyconover** [comment]
Actually just track this branch:

https://github.com/rustyconover/Amazon-DynamoDB/compare/feature/new-types

**Comment by stevecaldwell77** [comment]
I created a pull request on that branch for a test of some basic types that aren't currently supported.  I'll close this bug.
