### ISSUE TITLE
get_item: Global Secondary Indices

### ISSUE THREAD

**Issue by gykapur** [rustyconover/Amazon-DynamoDB#8]
Hi, I wouldn't be surprised if this is not an issue or I'm being a bit stupid, but I'm having some trouble using global secondary indices and the get_item method (or batch_get_item).  According to 
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html#GSI.Using the query should specify an IndexName parameter (kind of like 02-tables-gsi.t). Unfortunately, when I look at the code for Amazon::DynamoDB the IndexName parameter is not used in the _make_payload function.  If I am missing something, please let me know and excuse my stupidity.

Thanks.

**Comment by rustyconover** [comment]
Hello,

Query does work with global and local secondary indexes in my code.  Get item doesn't work with GSI it only works with the primary key of the table. Same with batch get item.  Both only lookup items by hash and schema key.  Only queries access the GSI and LSI.  That is my understanding, I could be wrong.  But I don't think so right now.

Rusty

**Comment by rustyconover** [comment]
Also IndexName is encoded in the query method and referenced online 1240. So it is getting built into the payload.
